name: Build & Test

on:
  push:
    branches: ['*']
  pull_request:
    branches: [master]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: self-hosted
    container:
        image: quantconnect/lean:foundation
        options: --cpus 12 --memory 12g
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run build and tests
        run: |
          # BuildDataProcessing
          # Build
          dotnet build /p:Configuration=Release /v:quiet /p:WarningLevel=1 Lean.DataSource.dYdXFundingRate.sln && \
          # Run Tests
          dotnet test ./DataProcessing.Tests/bin/Release/DataProcessing.Tests.dll

